### ISSUE TITLE
Add static library target similar to cbl-dll

### ISSUE THREAD

**Issue by guusw** [fragcolor-xyz/shards#151]

**Comment by sinkingsugar** [comment]
This got merged @guusw but before closing can you please disable this when building static target?
https://github.com/fragcolor-xyz/chainblocks/blob/6de764d56292f6bd689779d19911a431dfb611c3/cmake/Platform.cmake#L112-L116

**Comment by guusw** [comment]
I'll add a configure flag to enable/disable ubsan.
I think that's better than having it specifically disabled for the static library target, and easier to do since it's global

**Comment by guusw** [comment]
The target exists but Is currently hard to use since dependencies have to be linked against manually.
Should look into being able to generate this list usable for rust
