### ISSUE TITLE
Allow external variable of type `Any`

### ISSUE THREAD

**Issue by Kryptos-FR** [fragcolor-xyz/shards#159]
When defining an external variable, the actual type must be set beforehand. There are scenarios where it is not practical and instead it should be possible to set it as `Any` and have the chain execution sets the final type once data gets written into it.

**Comment by guusw** [comment]
This is mainly for output types I assume.

I'm not sure when compose/type checking is done but I image we can move it somewhere that when you run a chain with external variables it can run compose and fill in the external variable types.

**Comment by Kryptos-FR** [comment]
> This is mainly for output types I assume.

Yes only for variables that get written into. If the first access to an external variable is a read, then it should fail as current.
