### ISSUE TITLE
Consider renaming the DEBUG version of cbl

### ISSUE THREAD

**Issue by Kryptos-FR** [fragcolor-xyz/shards#183]
Often it is helpful to test both the `DEBUG` and `RELEASE` versions of `cbl` side-by-side.

As of now, they have the same name. We could add a "d" suffix for the `DEBUG` version.

**Comment by sinkingsugar** [comment]
I don't mind but with the current build, they won't be side by side anyway.

**Comment by Kryptos-FR** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/chainblocks/183?planning-poker) with ZenHub @guusw @sinkingsugar
