### ISSUE TITLE
Object picking

### ISSUE THREAD

**Issue by guusw** [fragcolor-xyz/shards#220]
As a creator/user I want to be able to select objects by clicking on them so I can perform further operation on them (view info, edit scripts, etc.)

This is completed once a picking mechanism is implemented, the actual operations are separate tasks.

**Comment by guusw** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/chainblocks/220?planning-poker) with ZenHub @Kryptos-FR @sinkingsugar

**Comment by sinkingsugar** [comment]
I'm curious on how it would be implemented, do you have any interesting idea with the new renderer @guusw ?

**Comment by guusw** [comment]
I'm thinking it would pick based on GFX.Drawable so you could select those.
If later we need the chain that contains it we could get it from there.

With this system it should be easy enough to do an extra pass for picking
Since this should eventually be async it could be structured like this with a separate pick command
```
(GFX.Render :View v) 
  - Queue render of frame t

(GFX.Pick :Location (x,y) :View v)
  - Pick from frame t-1
      This means a one frame delay
  - This blocks automatically causes a picking buffer
      to be rendered for view V when it is rendered
```

**Comment by sinkingsugar** [comment]
What do you return though? The drawables right?

**Comment by sinkingsugar** [comment]
also I guess the (x,y) could be the input

**Comment by guusw** [comment]
Probably return a drawable (or null/nothing) yeah, since it's can be a reference.
And yeah xy as input would be good, since you can chain it to mouse position easily
