### ISSUE TITLE
Split up actions per platform

### ISSUE THREAD

**Issue by guusw** [fragcolor-xyz/shards#224]
We should split up build actions per-platform, check this setup for reference from [libsdl-org/SDL](https://github.com/libsdl-org/SDL/actions)

This way it becomes easier to selectively push fixes for specific platforms and run only that build/test suite, and ignore the platform that the changes don't apply to.

**Comment by guusw** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/chainblocks/224?planning-poker) with ZenHub @Kryptos-FR @sinkingsugar

**Comment by Kryptos-FR** [comment]
It doesn't look like they did anything particular. They just split their workflow into several files but all get triggered in any pull-request regardless of what platforms has a change.

**Comment by guusw** [comment]
And it helps navigating the CI files a bit better too
