### ISSUE TITLE
Update the README

### ISSUE THREAD

**Issue by satendrapalsingh** [fragcolor-xyz/shards#225]
**Pitch**
As a developer new to the Chainblocks repository, I want to quickly understand and set it up, so that I may start contributing if interested.

**Acceptance criteria**
Update this project repository's README file to satisfy the parent [Epic's](https://github.com/fragcolor-xyz/management/issues/21) Acceptance Criteria, and additional criteria given below
- [ ] Add links to [building-chainblocks](https://docs.fragcolor.xyz/contribute/code/building-chainblocks/), [contributing code/docs](https://docs.fragcolor.xyz/contribute/),  [chainblocks-tutorials](https://learn.fragcolor.xyz/) & [chainblocks-examples repository](https://github.com/fragcolor-xyz/chainblocks-examples) documentation
- [ ] Run a grammar check on the finished text

**Additional context**
Refer to guidelines at [Github](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes), [freeCodeCamp](https://www.freecodecamp.org/news/how-to-write-a-good-readme-file/), [Make a Readme](https://www.makeareadme.com/), & [Awesome READMEs](https://github.com/matiassingers/awesome-readme).

**Comment by satendrapalsingh** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/chainblocks/225?planning-poker) with ZenHub @guusw @Kryptos-FR @sinkingsugar

**Comment by satendrapalsingh** [comment]
PR #237

**Comment by satendrapalsingh** [comment]
@Kryptos-FR This story needs a restimation. Not able to plan another round of poker-planning.

**Comment by Kryptos-FR** [comment]
@satendrapalsingh I removed the previous estimate and voted again. I think anyone can remove their own vote.

**Comment by satendrapalsingh** [comment]
@Kryptos-FR Yes I was able to re-estimate my own estimate.
