### ISSUE TITLE
Parameterize a wire before scheduling

### ISSUE THREAD

**Issue by Kryptos-FR** [fragcolor-xyz/shards#241]
**Pitch**
As a user, I want to be able to pass some arguments (or define constants visible) to a wire after creating it but before (or when) scheduling it, so that I can control some behaviours and/or variations of a wire externally.

**Acceptance criteria**
- [ ] zero or more parameters given to a wire prior to scheduling
- [ ] behave as if those values were hardcoded constants
- [ ] works with the native interface so that other languages (e.g. c# can use it)

**Details**
This avoids the need of variables for external values that shouldn't change during the execution of a wire but can't be hardcoded into the wire right away. Those parameters should acts as constant as if defined with a `(def)` function. In other words, it is different from an input value that might have been stored into a variable. That distinction is important as some shards (e.g. `(Http.Server)` don't accept variables for their parameters (e.g. `:Port`).

This would solve #240 without requiring a change in  `(Http.Server)` implementation.

**Comment by guusw** [comment]
Can this share the same functionality as external variables or is there a difference?

**Comment by Kryptos-FR** [comment]
@guusw An external variable is meant as a way to communicate between chains or for interop. Here it is more like a template or macro.

As if the edn text had a placeholder and this would inject the value before execution (or before evaluation, TBD). It is not meant to change once the chain is started, so from the chain point of view the value was always defined and constant.

We could have for instance (assuming the syntax would use `$`):
```clj
(defchain server
  (Http.Server :Port $port :Handler ...))
```

And then with this mechanism if we pass `7070` it would be equivalent to:
```clj
(def port 7070)
(defchain server
  (Http.Server :Port port :Handler ...))
```
or
```clj
(defchain server
  (Http.Server :Port 7070 :Handler ...))
```

Another syntax I was thinking of could be:
```clj
(def$ port 7070)
(defchain server
  (Http.Server :Port port :Handler ...))
```

That way, it has a default value and the evaluation can already check the type, but the value can be replaced before scheduling.

**Comment by sinkingsugar** [comment]
Old, can re-open if becomes relevant again. Using edn scripts solves most of it interleaved with actual code.
