### ISSUE TITLE
Document how to set up and use the Shards-Unity integration plugin

### ISSUE THREAD

**Issue by satendrapalsingh** [fragcolor-xyz/shards#243]
**Pitch**
As a game developer interested in using Fragnova assets in the Unity game engine, I want to know how to set up and use the Shards-Unity plugin so that I may be able to load/save Fragnova game assets in my Unity projects.

**Acceptance criteria**
A brief guide on how to set up and use the Chainblocks-Unity plugin.

**Additional context**
The document should be hosted at `https://docs.fragcolor.xyz/how-to/use-unity-plugin`.

**Comment by satendrapalsingh** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/chainblocks/243?planning-poker) with ZenHub @Kryptos-FR @sinkingsugar

**Comment by sinkingsugar** [comment]
Not sure on this... we need to release the plugin on the unity asset store... you mean this would be a pdf attached?

**Comment by satendrapalsingh** [comment]
I think we should have a page for this on our docs - probably `https://docs.fragcolor.xyz/plugins/unity-assets` or something
When we publish the plugin to Unity asset store we should have a link back to this.
IMO we should host/own the doc for our plugin.
