### ISSUE TITLE
Create a getting-started guide for Claymore

### ISSUE THREAD

**Issue by satendrapalsingh** [fragcolor-xyz/shards#245]
**Pitch**
As a game creator new to Fragcolor, I want an introductory guide to Claymore tools so that I may be able to start using them in my game projects.

**Acceptance criteria**
A beginner-friendly getting-started guide for Claymore and associated game development tools.

**Additional context**
Document should be hosted at `https://docs.fragcolor.xyz/how-to/use-claymore`.

**Comment by satendrapalsingh** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/chainblocks/245?planning-poker) with ZenHub @guusw @Kryptos-FR @sinkingsugar

**Comment by sinkingsugar** [comment]
Pointless now, we don't have enough substance

**Comment by satendrapalsingh** [comment]
Yeah, agree. I put it hear to just get it out on our roadmap.
I'm moving it to the product backlog.

@sinkingsugar , @Kryptos-FR
