### ISSUE TITLE
Document shards used in Euler samples

### ISSUE THREAD

**Issue by Kryptos-FR** [fragcolor-xyz/shards#248]
**Pitch**

From the external contribution at https://euler.color-rise.xyz/problems/, we have shards that are not fully documented yet. Since those are likely to be used frequently by users, they should be documented.

**Acceptance criteria**

- [x] Create and/or update the documentation the shards
- [x] Make sure there is at least one valid sample for each shard

**Shards**

- [x] [Assert.Is](https://docs.fragcolor.xyz/shards/Assert/Is/) -- already documented, added (details, more samples)
- [x] [Assert.IsNot](https://docs.fragcolor.xyz/shards/Assert/IsNot/) -- already documented, added (details, more samples)
- [x] [And](https://docs.fragcolor.xyz/shards/General/And/) --  sample added  (complete)
- [x] [ForRange](https://docs.fragcolor.xyz/shards/General/ForRange/) --  sample added (complete)
- [x] [If](https://docs.fragcolor.xyz/shards/General/If/) -- already documented (complete)
- [x] [Is](https://docs.fragcolor.xyz/shards/General/Is/) --  sample added, added (details, more samples)
- [x] [IsLess](https://docs.fragcolor.xyz/shards/General/IsLess/) --  sample added, added (details, more samples)
- [x] [IsLessEqual](https://docs.fragcolor.xyz/shards/General/IsLessEqual/) --  sample added, added (details, more samples)
- [x] [IsMore](https://docs.fragcolor.xyz/shards/General/IsMore/) --  sample added, added (details, more samples)
- [x] [IsMoreEqual](https://docs.fragcolor.xyz/shards/General/IsMoreEqual/) --  sample added, added (details, more samples)
- [x] [IsNot](https://docs.fragcolor.xyz/shards/General/IsNot/) --  sample added, added (details, more samples)
- [x] [Max](https://docs.fragcolor.xyz/shards/General/Max/) -- already documented, added (details, more samples)
- [x] [Min](https://docs.fragcolor.xyz/shards/General/Min/) -- already documented, added (details, more samples)
- [x] [Not](https://docs.fragcolor.xyz/shards/General/Not/) --  sample added (complete)
- [x] [Or](https://docs.fragcolor.xyz/shards/General/Or/) --  sample added (complete)
- [x] [ParseInt](https://docs.fragcolor.xyz/shards/General/ParseInt/) --  sample added (complete)
- [x] [Repeat](https://docs.fragcolor.xyz/shards/General/Repeat/) --  sample added (complete)
- [x] [Slice](https://docs.fragcolor.xyz/shards/General/Slice/) -- already documented (complete)
- [X] [Take](https://docs.fragcolor.xyz/shards/General/Take/) -- already documented, added (sample using variable)
- [x] [ToFloat](https://docs.fragcolor.xyz/shards/General/ToFloat/) --  sample added, added (details)
- [x] [ToInt](https://docs.fragcolor.xyz/shards/General/ToInt/) --  sample added, added (details)
- [x] [When](https://docs.fragcolor.xyz/shards/General/When/) -- already documented (complete)
- [x] [WhenNot](https://docs.fragcolor.xyz/shards/General/WhenNot/) -- already documented (complete)
- [x] [Math.Dec](https://docs.fragcolor.xyz/shards/Math/Dec/) -- already documented, added (details)
- [x] [Math.Inc](https://docs.fragcolor.xyz/shards/Math/Inc/) -- already documented, added (details)
- [x] [String.Join](https://docs.fragcolor.xyz/shards/String/Join/) --  sample added (complete)

**Comment by Kryptos-FR** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/chainblocks/248?planning-poker) with ZenHub @satendrapalsingh

**Comment by satendrapalsingh** [comment]
`Take` is documented too (current status of blocks/funcs [here](https://docs.google.com/spreadsheets/d/1Yh74gJHwo7eMrlgY4Sk2-5KKowfqiOfSK45TAKxjW4A/edit#gid=0)).
Have updated the story accordingly.

**Comment by Kryptos-FR** [comment]
@satendrapalsingh It is but it is missing some uses cases. I should have made it more clear.

Notably using a variable for the index:
```clj
1 >= .index
["a" "b" "c"] (Take .index)
```

**Comment by satendrapalsingh** [comment]
PR #289
