### ISSUE TITLE
Document all aliases for shards and functions

### ISSUE THREAD

**Issue by satendrapalsingh** [fragcolor-xyz/shards#257]
Add relevant alias information & sample code demonstrating usage, to applicable shards/functions as a `!!! note` section in their documentation, as already done for alias `|` for [`Sub`](https://docs.fragcolor.xyz/blocks/General/Sub/#details/).

- [x] `|` for [`Sub`](https://docs.fragcolor.xyz/shards/General/Sub/#details/)
- [x] `->` for [`defshards`](https://docs.fragcolor.xyz/functions/macros/#defshards) - not strictly alias, add section for `(->)` in `functions/misc#->`, fix descriptions in [`defshards`](https://docs.fragcolor.xyz/functions/macros/#defshards) & [`defn`](https://docs.fragcolor.xyz/functions/macros/#defn)  

Document shards and aliases - `Ref`, `Push`, `Set`, `Update`, and `Get`
- [x] `=` and ` &>` for [`Ref`](https://docs.fragcolor.xyz/shards/General/Ref/) - Assign a constant, meaning the variable cannot be assigned another value later.
- [x] `>>` for [`Push`](https://docs.fragcolor.xyz/shards/General/Push/) - Push to a sequence.
- [x] `>=` for [`Set`](https://docs.fragcolor.xyz/shards/General/Set/) - Creates and assign a mutable variable. Using it on an existing variable will generate a warning.
- [x] `>` for [`Update`]( https://docs.fragcolor.xyz/shards/General/Update/) - Sets a new value to an already defined mutable variable. Using it on a non-declared variable will generate an error.
- [x] `>==` for [`(Set :Global true)`](https://docs.fragcolor.xyz/shards/General/Set/)
- [x] ` >>!` for [`(Push :Clear false)`](https://docs.fragcolor.xyz/shards/General/Push/) - defines a sequence and pushes a value into it but for sequences), also retains variable value across wire itearations
- [x] `??` means `or` and is alias for [`(Get)`](https://docs.fragcolor.xyz/shards/General/Get/) with a default - `.var1 ?? 40` means `.var1 or 40` and it's alias for `(Get .var1 :Default 40)`

Also document other related shards - 
- [x] [`Table`](https://docs.fragcolor.xyz/shards/General/Table/) - declares a table variable with an empty key
- [x] [`Sequence`](https://docs.fragcolor.xyz/shards/General/Sequence/) - declares an empty sequence with specified element types
- [x] [`Const`](https://docs.fragcolor.xyz/shards/General/Const/) - specifies an unnamed const value (numbers, strings, sequences, tables)
- [x] [`Remove`](https://docs.fragcolor.xyz/shards/General/Remove/) - pop item from sequence based on predicate
- [x] [`Sort`](https://docs.fragcolor.xyz/shards/General/Sort/) - sort items in a sequence in ascending or descending order
- [x] [`Erase`](https://docs.fragcolor.xyz/shards/General/Erase/) - filter item from sequence based on indices
- [x] [`Count`](https://docs.fragcolor.xyz/shards/General/Count/) - counts characters/elements/key-value pairs in strings, sequences, tables
- [x] [`Swap`](https://docs.fragcolor.xyz/shards/General/Swap/) - will swap the values of two variables (swap possible between different type of variables - numeric, string, sequences, tables)
- [x] [`Clear`](https://docs.fragcolor.xyz/shards/General/Clear/) - clears up the whole sequence
- [x] [`Drop`](https://docs.fragcolor.xyz/shards/General/Drop/) - drops the last item from sequence
- [x] [`DropFront`](https://docs.fragcolor.xyz/shards/General/DropFront/) - drops the first item from sequence
- [x] [`Pop`](https://docs.fragcolor.xyz/shards/General/Pop/) - like Drop, but also returns the dropped element
- [x] [`PopFront`](https://docs.fragcolor.xyz/shards/General/PopFront/) - like PopFront, but also returns the dropped element
- [x] [`AppendTo`](https://docs.fragcolor.xyz/shards/General/AppendTo/) - append values to strings and sequences
- [x] [`PrependTo`](https://docs.fragcolor.xyz/shards/General/PrependTo/) - prepend values to strings and sequences

**Comment by Kryptos-FR** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/chainblocks/257?planning-poker) with ZenHub @satendrapalsingh

**Comment by satendrapalsingh** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/shards/257?planning-poker) with ZenHub @inabe-a @guusw @sinkingsugar

**Comment by satendrapalsingh** [comment]
PR #305

**Comment by sinkingsugar** [comment]
@sinkingsugar review
