### ISSUE TITLE
Add missing impl TryFrom<&Var> in Rust

### ISSUE THREAD

**Issue by inabe-a** [fragcolor-xyz/shards#263]
TryFrom implementations for some types are missing in types.rs

I've already started some of the work here:
https://github.com/fragcolor-xyz/shards/tree/rust_var_as_i32

Ideally we should cover/consolidate as many types as we can and clean up the code if necessary.

**Comment by Kryptos-FR** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/shards/263?planning-poker) with ZenHub @inabe-a @sinkingsugar
