### ISSUE TITLE
Add a runtime option to set the log level

### ISSUE THREAD

**Issue by Kryptos-FR** [fragcolor-xyz/shards#272]
Currently the logging level is set based on whether the build is in RELEASE or DEBUG (see function `setupSpdLog()` in  `runtime.cpp`). In DEBUG we might want to enable or disable the trace logs.

Add a runtime switch to enable/disable trace logs and use that value during setup.

Note: this will only affect DEBUG builds. In RELEASE, debug and trace logs should remain disabled.

**Comment by guusw** [comment]
`Add a runtime switch to enable/disable trace logs and use that value during setup.`
I'd add a way to set the level, e.g. `SHARDS_LOG=debug` or `SHARDS_LOG=trace` instead of just switching on/off

**Comment by guusw** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/shards/272?planning-poker) with ZenHub @inabe-a @Kryptos-FR @sinkingsugar

**Comment by sinkingsugar** [comment]
I'm against this as default.
It is intentional to completely omit the log levels at **compile-time** for obvious performance reasons.
I don't really want a runtime option in release mode.

**Comment by sinkingsugar** [comment]
Also apart from my disapproval. Such kind of task is not something we should do now.
