### ISSUE TITLE
Issues with the `Erase` shard

### ISSUE THREAD

**Issue by satendrapalsingh** [fragcolor-xyz/shards#316]
**Describe the bug**
- Issue 1: `Erase` gives an error if the input to it doesn't match the data structure of its `:Name` entity or the indices/keys passed to it.
- Issue 2: When erasing elements from a sequence `Erase` gives an error if the indices sequence is not in descending order
 

**To Reproduce**

Issue 1
```clj
{:k1 100 :k2 200 :k3 300} >= .tab
"Hello World"
(Erase ["k3" "k1"] .tab)
;; => [error] [2022-07-13 21:36:34.538] [T-10164] [runtime.cpp::1090] Error composing shard: Erase, invalid indices or malformed input., wire: main
```
Issue 2: case 1 (indices sequence sorted in ascending order)
```clj
[10 20 30 40 50] >= .seq
(Erase [1 2 3] .seq) ;; indices sorted in ascending order => error
;;[error] [2022-07-13 21:46:33.026] [T-16264] [runtime.cpp::791] Shard activation error, failed shard: Erase, error: Comparison < between two different value types
```

Issue 2: case 2 (indices sequence randomly sorted)
```clj
[10 20 30 40 50] >= .seq
(Erase [3 1 2] .seq) ;; indices sequence randomly sorted
.seq (Log) ;; .seq incorrectly filtered => [10, 30] ; expected .seq => [10, 50]
```

**Expected behavior**
- Issue 1: `Erase` should not validate the input as it does not use the input value for processing.
- Issue 2: `Erase` should work correctly for  indices sequence sorted by ascending order (case 1) as well as sorted randomly (case 2)

**Comment by sinkingsugar** [comment]
😭😭 @satendrapalsingh .
Erase USES Input, it manipulates INPUT

**Comment by sinkingsugar** [comment]
Skip this block for now as it's confusing me 😄 
Will try to review this soon.

**Comment by satendrapalsingh** [comment]
> Skip this block for now as it's confusing me 😄 Will try to review this soon.

Yeah, sure - no worries!

**Comment by guusw** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/shards/316?planning-poker) with ZenHub @inabe-a @Kryptos-FR @sinkingsugar
