### ISSUE TITLE
Generic function-like construct

### ISSUE THREAD

**Issue by guusw** [fragcolor-xyz/shards#321]
Using shards I want to be able to write a reusable piece of code that takes arbitrary inputs. 

Assume the following macro/wire:
```clj
(->
   >= .table ; Input is some kind of table
   (Take "Name")  >= .name
   (Take "Data") >= .data
   [.name .data] ; Return this sequence
)
```

The input table might be different: contain different members / different types for keys.

There should be a way to group this code into something that can be reused on different inputs.

### Current usage issues

Using `(defshards ...)` to wrap the code will cause it to insert the shards into the wire that uses the macro, causing the variables to leak into that scope and being unable to reassign their type.

Using `(defwire ...)` doesn't have a way to efficiently compose/execute with different types in different places 

### Possible solutions

- Some alternative to `(Do <wire>)` that internally copies the wire passed in so it can be composed by itself
- Change behavior of `(Do)` to cache permutations and automatically execute the correct variation
- Add arbitrary scope to make isolate variables

**Comment by sinkingsugar** [comment]
We got `defpure` for now that's enough.
