### ISSUE TITLE
Rewrite gfx shards to merge drawable-draw

### ISSUE THREAD

**Issue by guusw** [fragcolor-xyz/shards#322]
The current implementation was decided so more dynamic code could be written.

I think we can do a pass where we merge the current `(GFX.Drawable) into (GFX.Draw)` so it turns into a single shard that loads/creates and instance of something to draw and keeps track of it in the same shards.

To make previous dynamic usages possible we should add more ways to work with wires dynamically.

```clj
(Setup
  ... (Foreach (-> 
    (GFX.Drawable ...))) >=.drawables)
.drawables (GFX.Draw)
```

would turn into

```clj
(defloop drawable
  (GFX.Drawable ...))

(Setup 
  ... (Foreach (Spawn drawable)) >=.drawable-wires)

(Tick .drawable-wires) ;?something to run these wires
```

**Comment by sinkingsugar** [comment]
The case under can already work. Replace defwire with defloop and you don't need Tick. The chain is already spawned and scheduled by default.
Not sure how the loop will work though with gfx variable so maybe the Tick thing is needed. Which is Branch which we have already too (But can't run wire variable).

**Comment by sinkingsugar** [comment]
You can have the GFX on a top chain and have a chain under ran with Branch. The chain under will spawn those chains like above. And it works even today :)

**Comment by guusw** [comment]
Ah yes I meant defloop

**Comment by guusw** [comment]
So you mean this?
```clj
(defloop drawable
  (GFX.Drawable ...))

(Setup 
  ... (Foreach (Spawn drawable)) >=.drawable-wires)

(Branch .drawable-wires)

**Comment by sinkingsugar** [comment]
> So you mean this?
> 
> ```clojure
> (defloop drawable
>   (GFX.Drawable ...))
> 
> (Setup 
>   ... (Foreach (Spawn drawable)) >=.drawable-wires)
> 
> (Branch .drawable-wires) 
> ```

Yes but this would not work today, this would though:

```clojure
(defloop inner-loop
  ...)

(defwire fire-starter
  (Spawn inner-loop) <-- this will be spawned and will run in the MESH of Branch under
  )

(defloop main
  (Branch [fire-starter]) <-- this will create a new MESH that preserves the state of variables and ticks RIGHT HERE
  )
```

**Comment by sinkingsugar** [comment]
Functional version update
```clojure
(defloop inner-loop
  .root-variable
  (Log)
  (Pause 2.0))

(defwire fire-starter
  (Spawn inner-loop))

(defloop main
  (Setup "Hello" = .root-variable)
  (Branch [fire-starter]))

(schedule Root main)
(run Root 0.1 100)
```

**Comment by sinkingsugar** [comment]
> Functional version update
> 
> ```clojure
> (defloop inner-loop
>   .root-variable
>   (Log)
>   (Pause 2.0))
> 
> (defwire fire-starter
>   (Spawn inner-loop))
> 
> (defloop main
>   (Setup "Hello" = .root-variable)
>   (Branch [fire-starter]))
> 
> (schedule Root main)
> (run Root 0.1 100)
> ```

@guusw I think this is enough, especially cos in Claymore the GFX will be abstracted and everything will be in a Branch so everything will be Spawnable by default (inheriting GFX context).

I've tried adding a `(Prepare my-chain)` or `(Spawn my-chain :Schedule false)` but it felt quite some added complexity and limited too in terms of compose.

I think in a standalone script it might look like there are 2 indirections but in claymore there won't be.

**Comment by sinkingsugar** [comment]
I can see few cases where it might be useful though 🤔

**Comment by sinkingsugar** [comment]
Actually should already work as it is...

```
(defloop drawable
  (GFX.Drawable ...))

(Setup 
  ... (Foreach (Spawn drawable)))
```

Have you tried?
Issue is it will copy GFX variables captured, not sure if renders fine... something to fix/or prevent probably

**Comment by guusw** [comment]
Might not want to remove Draw after thinking about (It makes it harder to generate drawables from another thread)
I think for now I will add a helper that acts as `{...} (GFX.Drawable)(GFX.Draw :Queue .queue)` but in a single shard. Or add a check for the `:Queue` parameter and change behavior based on that

**Comment by guusw** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/shards/322?planning-poker) with Zenhub @Kryptos-FR @sinkingsugar @tdbe
