### ISSUE TITLE
Document enum values for applicable shards

### ISSUE THREAD

**Issue by satendrapalsingh** [fragcolor-xyz/shards#329]
Document actual enum values used in code for applicable shards.
And while at it also add any missing documentation to these shards - defintion help, input/output help, parameters description, code samples, etc.

57 shards

- [ ] 1. [`(FS.Copy)`](https://docs.fragcolor.xyz/shards/FS/Copy/) - add : details (enum values), definition/help, inputHelp, outputHelp, code samples
https://github.com/fragcolor-xyz/shards/tree/devel/src/core/shards/fs.cpp
  329,3:   enum class OverBehavior { Fail, Skip, Overwrite, Update };

- [ ] 2. [`(Math.Mean)`](https://docs.fragcolor.xyz/shards/Math/Mean/) - add : details (enum values), sample code
https://github.com/fragcolor-xyz/shards/tree/devel/src/core/shards/math.hpp
  634,3:   enum class MeanKind { Arithmetic, Geometric, Harmonic };

- [ ] 3. [`(LoadImage)`](https://docs.fragcolor.xyz/shards/General/LoadImage/) - add : details (enum values), definition/help, inputHelp, outputHelp, code samples
https://github.com/fragcolor-xyz/shards/tree/devel/src/core/shards/serialization.cpp
  254,3:   enum class BPP { u8, u16, f32 };

- [ ] 4. [`(TryMany)`](https://docs.fragcolor.xyz/shards/General/TryMany/) - add : details (enum values), definition/help, inputHelp, outputHelp
https://github.com/fragcolor-xyz/shards/tree/devel/src/core/shards/wires.cpp
  1187,1: enum class WaitUntil {

- [ ] 5. [`(Expand`](https://docs.fragcolor.xyz/shards/General/Expand/) - add : details (enum values), definition/help, inputHelp, outputHelp
https://github.com/fragcolor-xyz/shards/tree/devel/src/core/shards/wires.cpp
  1187,1: enum class WaitUntil {

- [ ] 6. [`(WireLoader)`](https://docs.fragcolor.xyz/shards/General/WireLoader/) - add : details (enum values), definition/help, inputHelp, outputHelp, code samples
https://github.com/fragcolor-xyz/shards/tree/devel/src/core/shards/wires.cpp
  14,1 enum RunWireMode { Inline, Detached, Stepped };

- [ ] 7. [`(WireRunner)`](https://docs.fragcolor.xyz/shards/General/WireRunner/) - add : details (enum values), definition/help, inputHelp, outputHelp, code samples
https://github.com/fragcolor-xyz/shards/tree/devel/src/core/shards/wires.cpp
  14,1 enum RunWireMode { Inline, Detached, Stepped };

- [ ] 8. [`(Audio.Oscillator)`](https://docs.fragcolor.xyz/shards/Audio/Oscillator/) - [add : details (enum values), ](https://docs.fragcolor.xyz/shards/Audio/Oscillator/)
https://github.com/fragcolor-xyz/shards/tree/devel/src/extra/audio.cpp
  489,3:   enum class Waveform { Sine, Square, Triangle, Sawtooth };

- [ ] 9. [`(GUI.Button)`](https://docs.fragcolor.xyz/shards/GUI/Button/) - add : details (enum values), definition/help, code samples
https://github.com/fragcolor-xyz/shards/tree/devel/src/extra/imgui.hpp
  26,3:   enum class GuiButton { Normal, Small, Invisible, ArrowLeft, ArrowRight, ArrowUp, ArrowDown };

- [ ] 10. [`(GUI.Table)`](https://docs.fragcolor.xyz/shards/GUI/Table/) - add : details (enum values), definition/help, code samples
https://github.com/fragcolor-xyz/shards/tree/devel/src/extra/imgui.hpp
  29,3:   enum class GuiTableFlags {

- [ ] 11. [`(GUI.SetupColumn)`](https://docs.fragcolor.xyz/shards/GUI/SetupColumn/) - add : details (enum values), definition/help, code samples
https://github.com/fragcolor-xyz/shards/tree/devel/src/extra/imgui.hpp
  38,3:   enum class GuiTableColumnFlags {

- [ ] 12. [`(GUI.TreeNode)`](https://docs.fragcolor.xyz/shards/GUI/TreeNode/) - add : details (enum values), definition/help, code samples
https://github.com/fragcolor-xyz/shards/tree/devel/src/extra/imgui.hpp
  46,3:   enum class GuiTreeNodeFlags {

- [ ] 13.  [`(GUI.Window)`](https://docs.fragcolor.xyz/shards/GUI/Window/) - GuiWindowFlags values already documented in `Attribute :Flags` => mention these are actual enum values
https://github.com/fragcolor-xyz/shards/tree/devel/src/extra/imgui.hpp
  59,3:   enum class GuiWindowFlags {

- [ ] 14. [`(GFX.BuiltinFeature)`](https://docs.fragcolor.xyz/shards/GFX/BuiltinFeature/) - add : details (enum values), definition/help, inputHelp, outputHelp, code samples 
https://github.com/fragcolor-xyz/shards/tree/devel/src/extra/gfx/feature.cpp
  20,3:   enum class Id {

- [ ] 15. [`(GFX.BuiltinMesh)`](https://docs.fragcolor.xyz/shards/GFX/BuiltinMesh/) - add : details (enum values), definition/help, inputHelp, outputHelp, code samples
https://github.com/fragcolor-xyz/shards/tree/devel/src/extra/gfx/mesh.cpp
  108,3:   enum class Type {

- [ ] 16. [`(GFX.Mesh)`](https://docs.fragcolor.xyz/shards/GFX/Mesh/) - add : details (enum values), definition/help, inputHelp, outputHelp, code samples 
https://github.com/fragcolor-xyz/shards/tree/devel/src/gfx/enums.hpp
  10,1: enum class WindingOrder { CW, CCW };

- [ ] 17. [`(Shader.ReadBuffer)`](https://docs.fragcolor.xyz/shards/Shader/ReadBuffer/) - add : details (enum values), definition/help, inputHelp, outputHelp, code samples
https://github.com/fragcolor-xyz/shards/tree/devel/src/gfx/shader/types.hpp
  12,1: enum class ShaderFieldBaseType { UInt8, Int8, UInt16, Int16, UInt32, Int32, Float16, Float32 };

- [ ] 18. [`(Shader.WriteGlobal)`](https://docs.fragcolor.xyz/shards/Shader/WriteGlobal/) - add : details (enum values), definition/help, inputHelp, outputHelp, code samples
https://github.com/fragcolor-xyz/shards/tree/devel/src/gfx/shader/types.hpp
  12,1: enum class ShaderFieldBaseType { UInt8, Int8, UInt16, Int16, UInt32, Int32, Float16, Float32 };

- [ ] 19. [`(Shader.ReadInput)`](https://docs.fragcolor.xyz/shards/Shader/ReadInput/) - add : details (enum values), definition/help, inputHelp, outputHelp, code samples
https://github.com/fragcolor-xyz/shards/tree/devel/src/gfx/shader/types.hpp
  12,1: enum class ShaderFieldBaseType { UInt8, Int8, UInt16, Int16, UInt32, Int32, Float16, Float32 };

- [ ] 20. [`(Shader.WriteOutput)`](https://docs.fragcolor.xyz/shards/Shader/WriteOutput/) - add : details (enum values), definition/help, inputHelp, outputHelp, code samples
https://github.com/fragcolor-xyz/shards/tree/devel/src/gfx/shader/types.hpp
  12,1: enum class ShaderFieldBaseType { UInt8, Int8, UInt16, Int16, UInt32, Int32, Float16, Float32 };

Can't find applicable shard

- [ ] 21. [`(ControllerTable.???)`](???) - add : details (enum values), 
https://github.com/fragcolor-xyz/shards/tree/devel/src/extra/xr.cpp
  19,1: enum class XRHand { Left, Right };

- [ ] 22. [`(HandTable.???)`](???) - add : details (enum values), 
https://github.com/fragcolor-xyz/shards/tree/devel/src/tests/test_runtime.cpp
  1077,1: enum class XRHand { Left, Right };

- [ ] 23. [`(GFX.???)`](???) - add : details (enum values), 
https://github.com/fragcolor-xyz/shards/tree/devel/src/gfx/context.hpp
  23,1: enum class ContextState {

- [ ] 24. [`(GFX.???)`](???) - add : details (enum values), 
https://github.com/fragcolor-xyz/shards/tree/devel/src/gfx/context.hpp
  30,1: enum class ContextFrameState {

- [ ] 25. [`(GFX.???)`](???) - add : details (enum values), 
https://github.com/fragcolor-xyz/shards/tree/devel/src/gfx/enums.hpp
  9,1: enum class PrimitiveType { TriangleList, TriangleStrip };

- [ ] 26. [`(GFX.???)`](???)  - add : details (enum values), 
https://github.com/fragcolor-xyz/shards/tree/devel/src/gfx/enums.hpp
  11,1: enum class ProgrammableGraphicsStage { Vertex, Fragment };

- [ ] 27. [`(GFX.???)`](???) - add : details (enum values), 
https://github.com/fragcolor-xyz/shards/tree/devel/src/gfx/enums.hpp
  12,1: enum class VertexAttributeType { UInt8, Int8, UNorm8, SNorm8, UInt16, Int16, UNorm16, SNorm16, UInt32, Int32, Float16, Float32 };

- [ ] 28. [`(GFX.???)`](???)  - add : details (enum values), 
https://github.com/fragcolor-xyz/shards/tree/devel/src/gfx/enums.hpp
  13,1: enum class IndexFormat { UInt16, UInt32 };

- [ ] 29. [`(GFX.???)`](???) - add : details (enum values), 
https://github.com/fragcolor-xyz/shards/tree/devel/src/gfx/pipeline_step.hpp
  10,1: enum class SortMode {

- [ ] 30. [`(GFX.???)`](???) - add : details (enum values), 
https://github.com/fragcolor-xyz/shards/tree/devel/src/gfx/texture.hpp
  12,1: enum class TextureFormatFlags : uint8_t {

- [ ] 31. [`(GFX.???)`](???)  - add : details (enum values), 
https://github.com/fragcolor-xyz/shards/tree/devel/src/gfx/texture.hpp
  20,1: enum class TextureType : uint8_t {

- [ ] 32. [`(GFX.???)`](???)  - add : details (enum values), 
https://github.com/fragcolor-xyz/shards/tree/devel/src/gfx/view.hpp
  19,1: enum class FovDirection {

- [ ] 33. [`(GFX.???)`](???) - add : details (enum values), 
https://github.com/fragcolor-xyz/shards/tree/devel/src/gfx/view.hpp
  31,1: enum class OrthographicSizeType {

- [ ] 34. [`(GFX.???)`](???) - add : details (enum values), 
https://github.com/fragcolor-xyz/shards/tree/devel/src/gfx/feature.hpp
  126,1: enum class ShaderParamFlags {

- [ ] 35. [`(GFX.???)`](???) - add : details (enum values), 
https://github.com/fragcolor-xyz/shards/tree/devel/src/gfx/features/debug_color.hpp
  14,3:   enum class Stage { Vertex, Fragment };

- [ ] 36. [`(GFX.???)`](???) - add : details (enum values), 
https://github.com/fragcolor-xyz/shards/tree/devel/src/gfx/shader/entry_point.hpp
  13,1: enum class DependencyType { Before, After };

- [ ] 37. [`(GFX.???)`](???) - add : details (enum values), 
https://github.com/fragcolor-xyz/shards/tree/devel/src/gfx/shader/generator.cpp
  193,1: enum class BufferType {

- [ ] 38. [`(GFX.???)`](???) - add : details (enum values), 
https://github.com/fragcolor-xyz/shards/tree/devel/src/gfx/tests/data.hpp
  14,1: enum class TestFrameFormat {

- [ ] 39. [`(???)`](???) - add : details (enum values), 
https://github.com/fragcolor-xyz/shards/tree/devel/src/extra/gfx/shards_types.hpp
  106,3:   enum class BlendFactor_ {

- [ ] 40. [`(???)`](???) - add : details (enum values), 
https://github.com/fragcolor-xyz/shards/tree/devel/src/extra/gfx/shards_types.hpp
  123,3:   enum class BlendOperation_ {

- [ ] 41. [`(???)`](???) - add : details (enum values), 
https://github.com/fragcolor-xyz/shards/tree/devel/src/extra/gfx/shards_types.hpp
  132,3:   enum class FilterMode_ {

- [ ] 42. [`(???)`](???)  - add : details (enum values), 
https://github.com/fragcolor-xyz/shards/tree/devel/src/extra/gfx/shards_types.hpp
  138,3:   enum class CompareFunction_ {

- [ ] 43. [`(???)`](???)  - add : details (enum values), 
https://github.com/fragcolor-xyz/shards/tree/devel/src/extra/gfx/shards_types.hpp
  151,3:   enum class ColorMask_ {

Can't find enum in shard parameter/input/output

- [ ] 44. [`(GUI.PlotBars)`](https://docs.fragcolor.xyz/shards/GUI/PlotBars/) - add : details (enum values), definition/help, code samples
https://github.com/fragcolor-xyz/shards/tree/devel/src/extra/imgui.cpp
  2594,3:   enum class Kind { unknown, xAndIndex, xAndY };

- [ ] 45. [`(GUI.PlotDigital)`](https://docs.fragcolor.xyz/shards/GUI/PlotDigital/) - add : details (enum values), definition/help, code samples
https://github.com/fragcolor-xyz/shards/tree/devel/src/extra/imgui.cpp
  2594,3:   enum class Kind { unknown, xAndIndex, xAndY };

- [ ] 46. [`(GUI.PlotLine)`](https://docs.fragcolor.xyz/shards/GUI/PlotLine/) - add : details (enum values), definition/help, code samples
https://github.com/fragcolor-xyz/shards/tree/devel/src/extra/imgui.cpp
  2594,3:   enum class Kind { unknown, xAndIndex, xAndY };

- [ ] 47. [`(GUI.PlotScatter)`](https://docs.fragcolor.xyz/shards/GUI/PlotScatter/) - add : details (enum values), definition/help, code samples
https://github.com/fragcolor-xyz/shards/tree/devel/src/extra/imgui.cpp
  2594,3:   enum class Kind { unknown, xAndIndex, xAndY };

Can't find enum values in code
- [ ] 48. [`(Sequence)`](https://docs.fragcolor.xyz/shards/General/Sequence) -  add : details (enum values), parameter help, definition/help, inputHelp, outputHelp, code samples

- [ ] 49. [`(Table)`](https://docs.fragcolor.xyz/shards/General/Table/) -  add : details (enum values), parameter help, definition/help, inputHelp, outputHelp, code samples

Shards for which enum not found 
- [ ] 50. [`(GUI.CheckboxFlags)`](https://docs.fragcolor.xyz/shards/GUI/CheckboxFlags/) -  add : details (enum values), parameter help, definition/help, inputHelp, outputHelp, code samples

Document after [`(GFX.Gizmo)`](https://docs.fragcolor.xyz/shards/GFX/Gizmo/) added

- [ ] 51. [`(GFX.Gizmo)`](https://docs.fragcolor.xyz/shards/GFX/Gizmo/) -  add : details (enum values), parameter help, definition/help, inputHelp, outputHelp, code samples
https://github.com/fragcolor-xyz/shards/tree/devel/src/extra/gizmo.hpp
  15,3:   enum class GridAxis { X, Y, Z };
https://github.com/fragcolor-xyz/shards/tree/devel/src/extra/gizmo.hpp
  20,3:   enum class Mode { Local, World };
https://github.com/fragcolor-xyz/shards/tree/devel/src/extra/gizmo.hpp
  25,3:   enum class Operation { Translate, Rotate, Scale, Universal };

Document after [`(GFX.EGUI)`](???) shards added

- [ ] 52. [`(GFX.EGUI.???)`](???) - add : details (enum values), 
https://github.com/fragcolor-xyz/shards/tree/devel/src/gfx/egui/egui_types.hpp
  46,1: enum class InputEventType : uint8_t {

- [ ] 53. [`(GFX.EGUI.???)`](???) - add : details (enum values), 
https://github.com/fragcolor-xyz/shards/tree/devel/src/gfx/egui/egui_types.hpp
  63,1: enum class TouchPhase : uint8_t {

- [ ] 54. [`(GFX.EGUI.???)`](???) - add : details (enum values), 
https://github.com/fragcolor-xyz/shards/tree/devel/src/gfx/egui/egui_types.hpp
  70,1: enum class PointerButton : uint8_t {

- [ ] 55. [`(GFX.EGUI.???)`](???)- add : details (enum values), 
https://github.com/fragcolor-xyz/shards/tree/devel/src/gfx/egui/egui_types.hpp
  151,1: enum class CursorIcon {

- [ ] 56. [`(GFX.EGUI.???)`](???) - add : details (enum values), 
https://github.com/fragcolor-xyz/shards/tree/devel/src/gfx/egui/egui_types.hpp
  224,1: enum class TextureFormat : uint8_t { R32F, RGBA8 };

**Comment by guusw** [comment]
Added enum values to documentation
See #472

**Comment by sinkingsugar** [comment]
@ChelseaChX what about this?

**Comment by ChelseaChX** [comment]
> @ChelseaChX what about this?

Let me check with Nicolas on what the plans for the enum values were/are. I have not touched on enum values yet, but I'll review the current status of it once I find out more.
