### ISSUE TITLE
Fix `(Table)` code example for usage of `(Push)`

### ISSUE THREAD

**Issue by satendrapalsingh** [fragcolor-xyz/shards#340]
The following two [`(Table)`](https://docs.fragcolor.xyz/shards/General/Table/) code samples have issues with the usage of [`(Push)`](https://docs.fragcolor.xyz/shards/General/Push/) (inconsistent results across platforms on the local machine as well as CI). Sometimes the `Push` works, sometimes it fails.

These samples were added as part of issue #257 and PR #305, and currently they are commented out.

Code example 1
```clj
;; without key, without types, local scope, using `Push` (puts sequence values)
(Table :Name .tableA)
.tableA (Log)         ;; created a table => {A: []}
1 (Push .tableA "A")
.tableA (Log)         ;; updated table => {A: [1]}
2 (Push .tableA "A") 
.tableA (Log)         ;; updated table => {A: [1, 2]}    
```

Code example 2
```clj
;; with key, single type, local scope, using `Push` (puts sequence values)
(Table .tableD :Key "A" :Types Type.Int)
.tableD (Log)         ;; created a table => {A: []}
10 (Push .tableD "A")
.tableD (Log)         ;; updated table => {A: [10]}
20 (Push .tableD "A") 
.tableD (Log)         ;; updated table => {A: [10, 20]}
```

So, 
- [ ] The behavior of `(Push)` on a table created by `(Table)` needs to be analyzed and fixed so that these code examples can work consistently.
- [ ] Test these code examples and then uncomment them on  [`(Table)`](https://docs.fragcolor.xyz/shards/General/Table/) documentation page

**Comment by sinkingsugar** [comment]
Use `Set` to showcase `Table` don't use `Push`.

**Comment by sinkingsugar** [comment]
@ChelseaChX

**Comment by ChelseaChX** [comment]
Seems to be fixed. We can close this issue.
