### ISSUE TITLE
Shards documentation of types is confusing

### ISSUE THREAD

**Issue by sinkingsugar** [fragcolor-xyz/shards#348]
<img width="234" alt="image" src="https://user-images.githubusercontent.com/7008900/183553344-ca56a452-6a1c-4987-8425-fb90b9918503.png">

What matters is Shards, not clojure/lisp side.
Follow `shards.h` upper case and explain that in the textual version there are aliases

**Comment by satendrapalsingh** [comment]
PR #351

**Comment by sinkingsugar** [comment]
@ChelseaChX still relevant?

**Comment by ChelseaChX** [comment]
> @ChelseaChX still relevant?

There will be a segment on types in the primer (it's there, just not reflected on the site yet!). I'll still check with Nicolas and Karan whether the current list of Types is accurate before closing this issue.
