### ISSUE TITLE
Rotation gizmo

### ISSUE THREAD

**Issue by guusw** [fragcolor-xyz/shards#352]
Functional in:
- [ ] 3 separate rotation axes
- [ ] Global space
- [ ] Local space

**Comment by guusw** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/shards/352?planning-poker) with ZenHub @Kryptos-FR @sinkingsugar

**Comment by sinkingsugar** [comment]
@guusw status?
