### ISSUE TITLE
Fix memory leaks

### ISSUE THREAD

**Issue by guusw** [fragcolor-xyz/shards#354]
Current issues to look at, might be related or separate:
- Memory leaks on android an get slower the longer the application runs
- Memory leaks on desktop (no noticable slowdown)

**Comment by guusw** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/shards/354?planning-poker) with ZenHub @Kryptos-FR @sinkingsugar

**Comment by sinkingsugar** [comment]
Is this fixed?

**Comment by guusw** [comment]
It was the texture view for the main output not being dropped, so unrelated to other textures, it would've been an issue in every sample utilizing graphics
