### ISSUE TITLE
Render inside egui panel/area

### ISSUE THREAD

**Issue by guusw** [fragcolor-xyz/shards#355]
We want to be able to take an area inside egui and be able to render arbitrary graphics to it (using GFX.Render).
Could be done using either render textures (in which case this needs #214, #172 ) or viewports

**Comment by guusw** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/shards/355?planning-poker) with ZenHub @Kryptos-FR @sinkingsugar

**Comment by Kryptos-FR** [comment]
I'm not sure to get what this issue is for. We already have panels and I am adding areas as well (that can be anchored to side and corner of the screen, with offsets).

**Comment by guusw** [comment]
Updated the description a bit, it's about being able to take an egui area an render some content to it
