### ISSUE TITLE
Execute a Wire from a string representation

### ISSUE THREAD

**Issue by Kryptos-FR** [fragcolor-xyz/shards#360]
Currently we can execute a Wire from a external file.

```clj
(WireLoader (Wire* "file.edn"))
```

We should be able to do it from a string in memory (for instance using a string context variable).

```clj
(WireLoader (Wire$ .code))
```

**Comment by Kryptos-FR** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/shards/360?planning-poker) with ZenHub @sinkingsugar @guusw

**Comment by sinkingsugar** [comment]
we got `EDN.Eval` now, clarify if this is still necessary? @Kryptos-FR

**Comment by Kryptos-FR** [comment]
Maybe it's not. We might want to revisit it once we have the online sandbox. But for now, let's close this issue.
