### ISSUE TITLE
egui integration (second batch)

### ISSUE THREAD

**Issue by Kryptos-FR** [fragcolor-xyz/shards#365]
Follows fragcolor-xyz/shards#267

**Acceptance criteria**
- [ ] close the feature gap with the former ImGui integration
  - [ ] all missing widgets
  - [ ] all missing parameters

**Comment by sinkingsugar** [comment]
where is the PR for this?

**Comment by sinkingsugar** [comment]
Also it's partially blocked majority of improvements don't need enums

**Comment by Kryptos-FR** [comment]
> where is the PR for this?

It is still in progress, so no PR yet.

**Comment by sinkingsugar** [comment]
@Kryptos-FR do we have a file picker? If not we need one quite soon.

**Comment by Kryptos-FR** [comment]
@sinkingsugar we don't have a file picker yet. Let's create a separate issue for it.
