### ISSUE TITLE
Explicitly and Clearly define what a "wire" and a "mesh" is on the Introduction page of Shards Documentation

### ISSUE THREAD

**Issue by aang114** [fragcolor-xyz/shards#393]
In the introduction page of the Shards Documentation, it straight-away starts talking about "wires" and "meshes".  
So it assumes that the reader already knows what a "wire" and a "mesh" are, when they don't! We should first define the terms "wire" and "mesh" are!

**Footnote:**

Introduction page of Shards Documentation Link: https://docs.fragcolor.xyz/shards/

**Comment by sinkingsugar** [comment]
I think we have a WIP shards primer document somewhere, @ShahFragcolor @ChelseaChX

**Comment by aang114** [comment]
Oh sorry I didn't know the "shards-examples" (https://github.com/fragcolor-xyz/shards-examples) repo is where all the issues for documentation is
