### ISSUE TITLE
Review GFX exposed variables

### ISSUE THREAD

**Issue by sinkingsugar** [fragcolor-xyz/shards#394]
For example this should have an `exposeVariables`
https://github.com/fragcolor-xyz/shards/blob/dadee5b293cb598e33fa376938eae4ce58791f08/src/extra/gizmos/context.cpp#L66

**Comment by guusw** [comment]
GizmoContext and MainWindow both only expose variables inside of the content shards so they should keep using data.shared instead of exposedVariables
