### ISSUE TITLE
GFX Crash in windows release

### ISSUE THREAD

**Issue by guusw** [fragcolor-xyz/shards#438]
When using graphics, shards crashes in windows on release mode using the vulkan backend

**Comment by sinkingsugar** [comment]
Hey @guusw , is this the case?

**Comment by Kryptos-FR** [comment]
@sinkingsugar still the case, hence why we need `export GFX_BACKEND=D3D12` before running in release.

**Comment by sinkingsugar** [comment]
That's weird/sad @guusw what's the reason?

**Comment by guusw** [comment]
Ok now that I found it I remember looking at it before, but this time I'll record here that it was because of stack space.

The vulkan driver calls a bunch of functions, wrapping MainWindow inside the following fixes it.
```clojure
(def test-wire (Wire "" :Looped :LStack
 ...
))
```

Maybe anyways we should increase the default stack size, currently it's 128kb (1MB in debug)

**Comment by sinkingsugar** [comment]
Hmm yeah I will think about it 👍
