### ISSUE TITLE
Fix ws tests

### ISSUE THREAD

**Issue by Kryptos-FR** [fragcolor-xyz/shards#451]
**Describe the bug**
The websocket tests (in file `src/tests/ws.edn` fail sometimes. This is likely due to the 3rd-party URLs we used that are unreliable.
> Warning:  [2022-10-31 09:29:35.797] [T-23290] [ws.cpp::218] WebSocket connection failed: Failed to resolve host
Error:  [2022-10-31 09:29:35.797] [T-23290] [runtime.cpp::755] Shard activation error, failed shard: WS.Client, error: WebSocket connection failed.
Error:  [2022-10-31 09:29:35.797] [T-23290] [runtime.cpp::755] Shard activation error, failed shard: Once, error: WebSocket connection failed.

**Proposed solution**
Setup a local websocket server that we maintain to be used as an echo service for the tests.

This serve could either always run (potentially dangerous: could cause DDoS attacks), or be brought up and down during the test themselves.

**Comment by sinkingsugar** [comment]
Extremely low priority.
