### ISSUE TITLE
Fix WGPU out of memory when repeatedly recreating contexts

### ISSUE THREAD

**Issue by guusw** [fragcolor-xyz/shards#468]
See https://github.com/fragcolor-xyz/shards/pull/466 where ui.edn recreates several windows, this runs out of memory on the CI machine in windows release.

**Comment by sinkingsugar** [comment]
Ouch, we need to find more leaks soon...

**Comment by sinkingsugar** [comment]
hey @guusw ? what about this?

**Comment by guusw** [comment]
I'm waiting a bit, technically it never happens only when the same program (re)creates multiple MainWindows so it's not critical (just tests do it)
I expect it to be fixed when we update wgpu-native along with the VR changes, I merged some changes into wgpu-native to allow it you to destroy the WGPUInstance which previously just kept existing globally.
