### ISSUE TITLE
Add enum help for rust enums

### ISSUE THREAD

**Issue by guusw** [fragcolor-xyz/shards#478]
Need to fill in the descriptions field in the `shenum`

I was thinking we can have:
```rs
shenum! {
  struct UIProperty {
    #[meta(help = "Returns the remaining space")]
    const RemainingSpace = 0x0;
  }
  struct UIPropertyInfo {}
}
```

Maybe @Kryptos-FR can look at it since you wrote the macros for it.

**Comment by guusw** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/shards/478?planning-poker) with Zenhub @Kryptos-FR @sinkingsugar

**Comment by sinkingsugar** [comment]
Mark low priority
