### ISSUE TITLE
Have UI.Area flip when a negative number is used for scale 

### ISSUE THREAD

**Issue by ShahFragcolor** [fragcolor-xyz/shards#482]
For UI.Area, currently making the scale a negative number makes the whole image disappear instead of mirror-ing it, is this a bug or is this intentional? 

Currently for my character I have another set of images for when the character is facing left. It would be easier to just mirror the scale to have it look left.

![image.png](https://images.zenhubusercontent.com/624187ee0cf085ebe2d9639f/d10d5425-e3f9-4e99-8426-6704989e6282)

**Comment by Kryptos-FR** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/shards/482?planning-poker) with Zenhub @guusw @sinkingsugar @tdbe

**Comment by guusw** [comment]
Just closing this for now,  we use sprites (quads) for the above example now. If the case ever arises for UI again we can reopen.
