### ISSUE TITLE
Shards lags when using large images in UI.

### ISSUE THREAD

**Issue by ShahFragcolor** [fragcolor-xyz/shards#484]
@ShahFragcolor commented on [Fri Dec 09 2022](https://github.com/fragcolor-xyz/rhythm-run/issues/81)

https://images.zenhubusercontent.com/460320683/22915413-bb2e-4dcc-8053-c95d27afff80/mainwindow_2022_12_06_09_35_54.mp4

- When using a large image in UI.Area the whole game  lags. Image is about (1920 x 1080)

https://images.zenhubusercontent.com/460320683/5943d89a-a782-4729-bc1a-128be3a4bff3/mainwindow_2022_12_06_09_50_24.mp4

- when using a smaller image, it does not lag

**Comment by ShahFragcolor** [comment]
https://user-images.githubusercontent.com/99865253/206677510-ce8f4f36-3b68-4f7d-9549-cf1ba9c65f49.mp4

currently as a whole my game seems to lag quite a bit, but it might be because in general i am still using images that are  too large and scaling them down

**Comment by guusw** [comment]
I suspect maybe the image is being loaded every frame, will check.

**Comment by sinkingsugar** [comment]
> I suspect maybe the image is being loaded every frame, will check.

Ouch let's fix that, either suggest better code to shah or fix the bug 🐜 asap as we want to publish the tutorial soon.

**Comment by guusw** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/shards/484?planning-poker) with Zenhub @Kryptos-FR @sinkingsugar @tdbe

**Comment by guusw** [comment]
Seems like it indeed is. Replacing the LoadImage with usage of
```clojure
(defshards LoadTexture [name]
  (LoadImage name)
  (GFX.Texture)
  )
```
seems like enough.

**Comment by guusw** [comment]
Maybe we should change UI.Image behavior with images to have some global cache or not accept images, since it's easy to make this mistake and cause the texture to be recreated every frame

**Comment by sinkingsugar** [comment]
we need to review the tutorial to catch those issues!  cc @ShahFragcolor 
@guusw I don't think so much the snipped you posted is very legit and people should learn that ideally, cos wires are stateful and indeed can cache things.
