### ISSUE TITLE
Update rapier

### ISSUE THREAD

**Issue by Kryptos-FR** [fragcolor-xyz/shards#488]
We use `rapier3D`  as the physics engine. It hasn't been updated for a while.

Tasks:
- [x] Update to a more recent version (ideally latest)
- [x] Add samples and test scripts

**Comment by Kryptos-FR** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/shards/488?planning-poker) with Zenhub @guusw @sinkingsugar @tdbe

**Comment by sinkingsugar** [comment]
also this is closed no? @Kryptos-FR
