### ISSUE TITLE
Review coroutines stack size

### ISSUE THREAD

**Issue by sinkingsugar** [fragcolor-xyz/shards#513]
Ok now that I found it I remember looking at it before, but this time I'll record here that it was because of stack space.

The vulkan driver calls a bunch of functions, wrapping MainWindow inside the following fixes it.
```clojure
(def test-wire (Wire "" :Looped :LStack
 ...
))
```

Maybe anyways we should increase the default stack size, currently it's 128kb (1MB in debug)

_Originally posted by @guusw in https://github.com/fragcolor-xyz/shards/issues/438#issuecomment-1370098354_

**Comment by guusw** [comment]
Maybe we can have a mechanism that during compose shards can request a certain amount of stack space (in this case MainWindow)

**Comment by Kryptos-FR** [comment]
Fixed by #514?

**Comment by sinkingsugar** [comment]
> Fixed by #514?

Not really but for now it's enough. Eventually we want to research some proper numbers on how many coroutines a big game/project will need.
