### ISSUE TITLE
Possible issue with type checking in Msg Shard or result type of ToString

### ISSUE THREAD

**Issue by Yttruire** [fragcolor-xyz/shards#672]
**Describe the bug**
--
When a value (e.g. `Int`) is converted into a `String` via the `ToString` shard and then passed to the `Msg` shard, it gives the following error whereby it seems that the type of the result of `ToString` is incorrect or undefined, or that `Msg` has an issue with type checking on the results of `ToString`:

```
[error] [2023-05-12 12:41:44.211] [T-21740] [SHCore.cpp::1193] Parameter validation failed: Parameter Message not accepting this kind of variable: & (valid types: String) shard: Msg
[error] [2023-05-12 12:41:44.211] [T-21740] [SHCore.cpp::1239] Failed parameter index: 0 line: 17 shard: Msg
```

There is no error when `Msg` is called on a normal `String` that has not undergone `ToString` type conversion

**To Reproduce**
--
The following code block will result in the above issue
```
(defmesh main)
(defshards test-shard [test-value]
  test-value (ToString) >= .local-test
  ;; (IsString) (Log) ;; If this line is run, it will output true, so it is might not be a (ToString) bug
  (Msg .local-test)
  ;; (Msg "Normal string") ;; if this line is run, there is no error
)

(defwire example
  (test-shard 3))

(schedule main example)
(run main 1 1)
```

**Expected behavior**
--
It should print "3" normally

**Comment by sinkingsugar** [comment]
By design `Msg` only outputs a "message" so a string.
Do `.local-test (Log)` to output variable value.

**Comment by Yttruire** [comment]
This issue has been clarified. Refer to #673 for a follow-up bug regarding the printed error message.

The behavior that the Msg shard cannot print the value of variables is intentional but not fully correct (as it can still print the value of argument variables). Refer to #674 for the follow up to this issue, and [here ](https://github.com/fragcolor-xyz/shards-examples/issues/66)for the respective issue in documentation.
