### ISSUE TITLE
Parameter validation failure may print "&" instead of the actual type of the given variable

### ISSUE THREAD

**Issue by Yttruire** [fragcolor-xyz/shards#673]
**Describe the bug**
--
It is sometimes the case that a parameter validation failure due to type mismatch in the parameters would print the type of the given argument is "&" instead of its actual type. Possibly an issue with the logger printing the type of the variable before the type has been resolved.

```
[error] [2023-05-12 14:18:26.409] [T-7872] [SHCore.cpp::1193] Parameter validation failed: Parameter Message not accepting this kind of variable: & (valid types: String) shard: Msg    
[error] [2023-05-12 14:18:26.411] [T-7872] [SHCore.cpp::1239] Failed parameter index: 0 line: 17 shard: Msg
```

**To Reproduce**
--
```
(defwire example
  (Msg .undeclared))

(schedule main example)
(run main 1 1)
```
or 
```
(defwire example
  3 (ToString) >= .test-value
  (Msg .test-value))

(schedule main example)
(run main 1 1)
```

**Expected behavior**
--
The error should clearly output the type of the given variable rather than a symbol "&".

**Comment by guusw** [comment]
It uses the same formatter as the docs (so `&` means ContextVar but it looks weird without any following type).
I should probably say `&String`, the formatter probably doesn't have any context to get the type from, which can maybe be added.
