### ISSUE TITLE
Vector literal after new line after no params & no () shard decl should parse as vector

### ISSUE THREAD

**Issue by ccfontes** [fragcolor-xyz/shards#774]
**Describe the bug**
Declaring vector literal at start of line, causes the vector literal to be parsed as parameters to a shard at the end of previous line, when this shard is declared without parameters and doesn't use `()`.

**To Reproduce**
Running this code:
```dart
(23 45 56) | ToColor | Log
(23 45 56) | ToColor | Log
```
results in this error:
```
[error] [2023-08-30 23:37:15.126] [T-9974730] [runtime.cpp::3195] Fatal error: Parameter Prefix not accepting this kind of variable: Int (valid types: String), line: 254, column: 24 shard: Log
thread '<unnamed>' panicked at 'Failed to evaluate file: ShardsError { message: "Failed to set parameter (3), error: Set parameter validation failed", loc: LineInfo { line: 254, column: 24 } }', src/cli.rs:160:63
```

**Expected behavior**
Declaring a literal such as `(x1, x2, ..)` at the start of a line, should still be interpreted as a vector, even when the previous line ends with a shard declared without parameters and not using `()`.

**Comment by sinkingsugar** [comment]
Fixed in #820
